In [12]:
from dataclasses import dataclass
import torch

In [4]:
class NewX:
    x: int

In [5]:
@dataclass
class NewDataX:
    x: int

In [11]:
ndx = NewDataX(4)
ndx2 = NewDataX()

TypeError: NewDataX.__init__() missing 1 required positional argument: 'x'

In [10]:
nx = NewX()
nx.x

AttributeError: 'NewX' object has no attribute 'x'

In [20]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
t

tensor([1., 2., 3.])

In [18]:
t.requires_grad_(True)

tensor([1., 2., 3.], requires_grad=True)

In [19]:
t

tensor([1., 2., 3.], requires_grad=True)